# Generated by Django 6.0.4 on 2026-04-24 22:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('orders', '0003_remove_order_order_waybill_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('accent_color', models.CharField(default='#198754', max_length=7)),
                ('sidebar_color', models.CharField(default='#2f3542', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مظهر النظام',
                'verbose_name_plural': 'مظهر النظام',
            },
        ),
        migrations.CreateModel(
            name='TreasuryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('internal', 'خزنة داخلية'), ('external', 'خزنة خارجية')], max_length=20, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'حساب خزنة',
                'verbose_name_plural': 'حسابات الخزنة',
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ExternalShipmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دفعة شحن خارجي',
                'verbose_name_plural': 'دفعات الشحن الخارجي',
                'ordering': ['-imported_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'مدير عام'), ('admin', 'مسؤول'), ('user', 'مستخدم')], default='user', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_label', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', '-last_seen_at'], name='clientsess_user_seen')],
            },
        ),
        migrations.CreateModel(
            name='ExternalShipmentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_data', models.JSONField(default=dict)),
                ('profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.externalshipmentbatch')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['batch'], name='extrow_batch_idx')],
            },
        ),
        migrations.CreateModel(
            name='TreasuryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('direction', models.CharField(choices=[('in', 'وارد'), ('out', 'منصرف')], default='in', max_length=3)),
                ('reason', models.CharField(choices=[('order_delivered_profit', 'ربح من تسليم أوردر'), ('order_accounted', 'تسوية حاسب أنت'), ('manual', 'يدوي'), ('profit_internal', 'أرباح داخلية'), ('profit_external', 'أرباح خارجية'), ('adjustment', 'تسوية / تعديل'), ('other', 'أخرى')], default='other', max_length=40)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.treasuryaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_entries', to='orders.order')),
            ],
            options={
                'verbose_name': 'حركة خزنة',
                'verbose_name_plural': 'حركات الخزنة',
                'ordering': ['-entry_date', '-id'],
                'indexes': [models.Index(fields=['entry_date', 'account'], name='treasury_date_acc_idx')],
            },
        ),
    ]
