# Generated by Django 6.0.4 on 2026-04-29 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegates', '0006_delegatesettlementitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(db_index=True)),
                ('advance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('work_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='delegates.delegate')),
            ],
            options={
                'ordering': ['-metric_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('delegate', 'metric_date'), name='delegate_daily_metric_unique')],
            },
        ),
    ]
