# Generated by Django 6.0.4 on 2026-04-22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("delegates", "0001_initial"),
        ("merchants", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="order",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="merchants.merchant",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delegate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="delegates.delegate",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("delivered", "تم التسليم"),
                    ("in_transit", "في الطريق"),
                    ("accounted", "حاسب أنت"),
                ],
                default="in_transit",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="waybill_number",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="رقم البوليصة لازم يبدأ بـ BRB وبعده أرقام فقط. مثال: BRB12345",
                        regex="^BRB\\d+$",
                    )
                ],
            ),
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_date", "-id"]},
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["waybill_number"], name="order_waybill_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="order_status_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_date"], name="order_date_idx"),
        ),
    ]

