# Generated by Django 6.0.4 on 2026-04-24 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_fields_and_relations'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_waybill_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_date_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='external_waybill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='waybill_number',
            field=models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='رقم البوليصة لازم يبدأ بـ BRB وبعده أرقام فقط. مثال: BRB12345', regex='^BRB\\d+$')]),
        ),
    ]
