# Generated by Django 6.0.4 on 2026-04-23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("delegates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegate",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=5),
        ),
        migrations.AddField(
            model_name="delegate",
            name="fixed_deduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="DelegateTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transaction_date", models.DateField(default=django.utils.timezone.localdate)),
                ("tx_type", models.CharField(choices=[("advance", "عهدة"), ("transfer", "تحويل"), ("deposit", "توريد")], max_length=20)),
                ("direction", models.CharField(choices=[("in", "داخل"), ("out", "خارج")], default="in", max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delegate",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="delegates.delegate"),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="delegatetransaction",
            index=models.Index(fields=["transaction_date"], name="delegatetx_date_idx"),
        ),
    ]

