# Generated by Django 6.0.4 on 2026-04-24 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegates', '0002_delegate_settlement_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateDailyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_date', models.DateField(db_index=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_closes', to='delegates.delegate')),
            ],
            options={
                'verbose_name': 'توريد يومي (مندوب)',
                'verbose_name_plural': 'توريدات يومية',
                'ordering': ['-close_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('delegate', 'close_date'), name='delegate_daily_close_unique')],
            },
        ),
    ]
