# Generated by Django 6.0.4 on 2026-04-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegates', '0003_step1_db_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegatetransaction',
            name='delegate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_transactions', to='delegates.delegate'),
        ),
    ]
