# Generated by Django 6.0.4 on 2026-04-29 01:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegates', '0005_delegate_linked_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateSettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('title', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('kind', models.CharField(choices=[('accounted', 'حاسب أنت'), ('advance', 'عهدة'), ('other', 'أخرى')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_items', to='delegates.delegate')),
            ],
            options={
                'ordering': ['-item_date', '-id'],
            },
        ),
    ]
