# Generated by Django 6.0.4 on 2026-04-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatthread_chatmessage_orderrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدير عام'), ('admin', 'مسؤول'), ('user', 'مستخدم'), ('merchant', 'تاجر'), ('delegate', 'مندوب')], default='user', max_length=20),
        ),
    ]
