# Generated by Django 6.0.4 on 2026-05-05 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_apperrorlog'),
        ('orders', '0006_soft_delete_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('code', models.SlugField(blank=True, max_length=40)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'فروع',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('from_entity', models.CharField(db_index=True, max_length=128)),
                ('to_entity', models.CharField(db_index=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('entry_type', models.CharField(choices=[('collection', 'تحصيل'), ('shipping_income', 'دخل الشحن'), ('courier_commission', 'عمولة مندوب'), ('courier_salary', 'مرتب مندوب'), ('handover', 'توريد (مندوب → شركة)'), ('cash_out', 'صرف (شركة → مندوب)'), ('transfer', 'تحويل (مندوب ↔ مندوب)'), ('merchant_advance', 'عربون تاجر'), ('merchant_payment', 'حركة حساب تاجر'), ('adjustment', 'تعديل / تسوية'), ('inventory_movement', 'مخزون / مرتجع')], db_index=True, max_length=32)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.branch')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.order')),
            ],
            options={
                'verbose_name': 'قيد دفتر',
                'verbose_name_plural': 'قيود الدفتر',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order', 'entry_type'], name='ledger_order_type_idx'), models.Index(fields=['branch', '-created_at'], name='ledger_branch_created_idx')],
            },
        ),
    ]
