# Generated by Django 6.0.4 on 2026-05-05 02:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_branch_ledger_operational_extend'),
        ('delegates', '0008_soft_delete_fields'),
        ('merchants', '0005_soft_delete_fields'),
        ('orders', '0007_branch_ledger_operational_extend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(db_index=True, default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, help_text='من سعر الشحن (مثل ٠٫٧٥ = ٧٥٪)', max_digits=7)),
                ('fixed_addon', models.DecimalField(decimal_places=2, default=0, help_text='يُستخدم لاستثناءات بسيطة لكل طلب مطابق', max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='core.branch')),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='delegates.delegate')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'قاعدة عمولة',
                'verbose_name_plural': 'قواعد العمولة',
                'ordering': ['-priority', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('partial', 'جزئي'), ('closed', 'مسدَّد أو مغلق')], db_index=True, default='open', max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='delegates.delegate')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='merchants.merchant')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='orders.order')),
            ],
            options={
                'verbose_name': 'سجل مديونية',
                'verbose_name_plural': 'الديون والمستحقّات',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DebtRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='core.debt')),
            ],
            options={
                'verbose_name': 'سداد دَين',
                'verbose_name_plural': 'سدادات الديون',
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MerchantStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, db_index=True, max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'صنف مخزون',
                'verbose_name_plural': 'أصناف المخزون',
                'ordering': ['merchant_id', 'label'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='موجب زيادة، سالب نقصان')),
                ('reason', models.CharField(choices=[('receipt', 'استلام مخزون'), ('return_order', 'مرتجع شحنة'), ('adjust', 'تسوية أو تعديل'), ('transfer_out', 'صادر داخلي'), ('other', 'أخرى')], default='adjust', max_length=32)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.merchantstockitem')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات مخزون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'عرض في النظام'), ('wa_pending', 'بانتظار واتساب'), ('mail_pending', 'بانتظار بريد')], db_index=True, default='in_app', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'إشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(db_index=True, help_text='مفتاح المجموعة مثل price_change أو debt_waiver', max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=14)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'موافقة إجراء',
                'verbose_name_plural': 'موافقة الإجراءات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['status'], name='debt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantstockitem',
            index=models.Index(fields=['merchant', 'label'], name='stk_merchant_label_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantstockitem',
            index=models.Index(fields=['merchant', 'sku_code'], name='stk_merchant_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['item', '-created_at'], name='invmov_item_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['user', '-created_at'], name='nf_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sensitiveapprovalrequest',
            index=models.Index(fields=['status'], name='saf_status_idx'),
        ),
    ]
