# Generated by Django 6.0.4 on 2026-04-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegates', '0004_alter_delegatetransaction_delegate'),
        ('merchants', '0003_alter_merchant_name'),
        ('orders', '0004_step1_db_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('add', 'إضافة'), ('subtract', 'خصم')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_transactions', to='delegates.delegate')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegate_transactions', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('add', 'إضافة'), ('subtract', 'خصم')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='merchants.merchant')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_transactions', to='orders.order')),
            ],
        ),
    ]
