# Generated by Django 6.0.4 on 2026-05-05 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_branch_ledger_operational_extend'),
        ('orders', '0006_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'تم التسليم'), ('in_transit', 'في الطريق'), ('accounted', 'حاسب أنت'), ('partially_delivered', 'تسليم جزئي'), ('partially_delivered_with_return', 'تسليم جزئي مع مرتجع'), ('returned', 'مرتجع'), ('postponed', 'مؤجل')], db_index=True, default='in_transit', max_length=48),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
