# Generated by Django 6.0.4 on 2026-05-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_branch_ledger_operational_extend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'تم التسليم'), ('in_transit', 'في الطريق'), ('accounted', 'حاسب أنت'), ('partially_delivered', 'تسليم جزئي'), ('partially_delivered_with_return', 'تسليم جزئي مع مرتجع'), ('returned', 'مرتجع'), ('postponed', 'مؤجل'), ('paid_to_company', 'مدفوع للشركة شامل الشحن')], db_index=True, default='in_transit', max_length=48),
        ),
    ]
